// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xmbardirxjhdamaeiuhx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhtYmFyZGlyeGpoZGFtYWVpdWh4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkwMDY1MzgsImV4cCI6MjA3NDU4MjUzOH0.THBzUZJKhiSSlbzF_cB3-LI2Ndw1vvJsY_awzSF2SaM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});